import re
import asyncio
from datetime import datetime, timezone
from typing import Dict, Any, List
from sqlalchemy import select, delete, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import AsyncSessionLocal
from app.models.category import EventCategory
from app.models.event import Event, EventSchedule
from app.models.registration import Registration
from app.models.knowledge import KnowledgeBase
from app.services.rag_engine import rag_engine

# 37 High Quality Unsplash Images (16:9, Tech, AI, Conferences - 100% Unique URLs)
IMAGES = {
    "ai_summit": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "fintech": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "cybersecurity": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "greentech": "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "cloud_devops": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "uiux": "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "techfest": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "blockchain": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "ai_ethics": "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "langgraph": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "smart_mfg": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "game_dev": "https://images.unsplash.com/photo-1511512578047-dfb367046420?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "robotics": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "semiconductor": "https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "data_eng": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "medtech": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "edtech": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "smartcity": "https://images.unsplash.com/photo-1519501025264-65ba15a82390?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "agritech": "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "hackathon": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    # 17 NEW UNIQUE IMAGES (17 SỰ KIỆN MỚI)
    "logistics": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "ev_mobility": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "quantum": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "ecommerce": "https://images.unsplash.com/photo-1556742049-0a67c5574f73?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "hr_tech": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "proptech": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "opensource": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "spacetech": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "aimarketing": "https://images.unsplash.com/photo-1542744094-3a31727221eb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "biotech": "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "telecom_edge": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "spatial_arvr": "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "insurtech": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "cleantech": "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "cyberdrill": "https://images.unsplash.com/photo-1563986768609-322da13575f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "web3gaming": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    "cio_summit": "https://images.unsplash.com/photo-1515187029135-18ee286d815b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
}

CATEGORIES_DATA = [
    {"code": "AI", "name": "Trí Tuệ Nhân Tạo & AI"},
    {"code": "FINTECH", "name": "Công Nghệ Tài Chính & Fintech"},
    {"code": "CYBERSECURITY", "name": "An Ninh Mạng & Bảo Mật"},
    {"code": "GREENTECH", "name": "Năng Lượng Xanh & Net Zero"},
    {"code": "CLOUD", "name": "Điện Toán Đám Mây & DevOps"},
    {"code": "UIUX", "name": "Thiết Kế Trải Nghiệm & UI/UX"},
    {"code": "STARTUP", "name": "Khởi Nghiệp & Đổi Mới Sáng Tạo"},
    {"code": "BLOCKCHAIN", "name": "Web3 & Blockchain"},
    {"code": "SOFTWARE", "name": "Kỹ Thuật Phần Mềm & Game"},
    {"code": "DIGITAL", "name": "Chuyển Đổi Số Doanh Nghiệp"},
    {"code": "ROBOTICS", "name": "Robot & Tự Động Hóa"},
    {"code": "SEMICONDUCTOR", "name": "Bán Dẫn & Thiết Kế Vi Mạch"},
    {"code": "DATA", "name": "Dữ Liệu & Big Data"},
    {"code": "MEDTECH", "name": "Y Tế Thông Minh & MedTech"},
    {"code": "EDTECH", "name": "Giáo Dục & EdTech"},
    {"code": "SMARTCITY", "name": "Đô Thị Thông Minh & IoT"},
    {"code": "AGRITECH", "name": "Nông Nghiệp Công Nghệ Cao"},
    {"code": "HACKATHON", "name": "Cuộc Thi AI & Hackathon"},
    {"code": "LOGISTICS", "name": "Logistics & Chuỗi Cung Ứng"},
    {"code": "DEEPTECH", "name": "Công Nghệ Sâu & Lượng Tử"},
]

RAW_EVENTS: List[Dict[str, Any]] = [
    # 4 FEATURED EVENTS (4 DIVERSE PILLARS: AI, FINTECH, CYBERSECURITY, GREEN TECH)
    {
        "title": "AI Summit Vietnam 2026: Kiến Tạo Tương Lai Số",
        "slug": "ai-summit-vietnam-2026",
        "category_code": "AI",
        "event_type": "Trí Tuệ Nhân Tạo",
        "location": "Trung Tâm Hội Nghị Quốc Gia (NCC), Hà Nội",
        "location_address": "Đại lộ Thăng Long, Mễ Trì, Nam Từ Liêm, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=National+Convention+Center+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "10/10/2026 08:30",
        "end_date": "11/10/2026 17:30",
        "start_time": datetime(2026, 10, 10, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 11, 17, 30, tzinfo=timezone.utc),
        "capacity": 1000,
        "registered_count": 780,
        "status": "PUBLISHED",
        "featured": True,
        "homepage_visible": True,
        "homepage_order": 1,
        "cover_image": IMAGES["ai_summit"],
        "description": "Hội nghị thượng đỉnh quy tụ hơn 1,000 chuyên gia, CEO và nhà nghiên cứu AI hàng đầu thế giới thảo luận về Generative AI, Autonomous Agents, LLM trong doanh nghiệp và chiến lược chủ quyền dữ liệu quốc gia.",
    },
    {
        "title": "Fintech Vietnam Open Banking & Payment Summit 2026",
        "slug": "fintech-vietnam-open-banking-payment-summit-2026",
        "category_code": "FINTECH",
        "event_type": "Công Nghệ Tài Chính",
        "location": "Khách sạn Lotte Hotel Hanoi",
        "location_address": "54 Liễu Giai, Phường Cống Vị, Quận Ba Đình, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Lotte+Hotel+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "20/10/2026 08:30",
        "end_date": "21/10/2026 17:00",
        "start_time": datetime(2026, 10, 20, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 21, 17, 0, tzinfo=timezone.utc),
        "capacity": 700,
        "registered_count": 540,
        "status": "PUBLISHED",
        "featured": True,
        "homepage_visible": True,
        "homepage_order": 2,
        "cover_image": IMAGES["fintech"],
        "description": "Diễn đàn tài chính công nghệ phân tích xu hướng ngân hàng mở (Open Banking), thanh toán số xuyên biên giới theo chuẩn QR quốc tế, sinh trắc học và AI phòng chống gian lận tài chính.",
    },
    {
        "title": "Cybersecurity & Data Privacy Forum 2026",
        "slug": "cybersecurity-data-privacy-forum-2026",
        "category_code": "CYBERSECURITY",
        "event_type": "An Ninh Mạng",
        "location": "Khách sạn JW Marriott Hanoi",
        "location_address": "Số 8 Đỗ Đức Dục, Mễ Trì, Nam Từ Liêm, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=JW+Marriott+Hotel+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "28/09/2026 08:30",
        "end_date": "29/09/2026 17:00",
        "start_time": datetime(2026, 9, 28, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 9, 29, 17, 0, tzinfo=timezone.utc),
        "capacity": 600,
        "registered_count": 520,
        "status": "PUBLISHED",
        "featured": True,
        "homepage_visible": True,
        "homepage_order": 3,
        "cover_image": IMAGES["cybersecurity"],
        "description": "Diễn đàn an ninh thông tin cấp cao về phòng chống mã độc tống tiền (Ransomware), bảo mật kiến trúc Zero Trust, an ninh dữ liệu đám mây và tuân thủ nghị định bảo vệ dữ liệu cá nhân (PDPD).",
    },
    {
        "title": "Green Tech & Năng Lượng Tái Tạo Summit Vietnam 2026",
        "slug": "green-tech-nang-luong-tai-tao-summit-2026",
        "category_code": "GREENTECH",
        "event_type": "Chuyển Đổi Xanh",
        "location": "Trung Tâm Hội Nghị White Palace Hoàng Văn Thụ, TP.HCM",
        "location_address": "194 Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=White+Palace+Hoang+Van+Thu&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "05/11/2026 09:00",
        "end_date": "06/11/2026 17:00",
        "start_time": datetime(2026, 11, 5, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 6, 17, 0, tzinfo=timezone.utc),
        "capacity": 800,
        "registered_count": 610,
        "status": "PUBLISHED",
        "featured": True,
        "homepage_visible": True,
        "homepage_order": 4,
        "cover_image": IMAGES["greentech"],
        "description": "Chiến lược chuyển đổi năng lượng xanh hướng tới Net Zero 2050, lưu trữ pin thông minh quy mô lưới điện, tín chỉ carbon và các công nghệ giảm phát thải công nghiệp tiên tiến.",
    },

    # 16 OTHER DIVERSE REALISTIC EVENTS (SEPTEMBER TO NOVEMBER 2026)
    {
        "title": "Vietnam Cloud & DevOps Expo 2026",
        "slug": "vietnam-cloud-devops-expo-2026",
        "category_code": "CLOUD",
        "event_type": "Điện Toán Đám Mây",
        "location": "GEM Center, TP. Hồ Chí Minh",
        "location_address": "Số 8 Nguyễn Bỉnh Khiêm, Phường Đa Kao, Quận 1, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=GEM+Center+Ho+Chi+Minh&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "12/11/2026 09:00",
        "end_date": "13/11/2026 17:00",
        "start_time": datetime(2026, 11, 12, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 13, 17, 0, tzinfo=timezone.utc),
        "capacity": 800,
        "registered_count": 560,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 5,
        "cover_image": IMAGES["cloud_devops"],
        "description": "Sự kiện chuyên ngành về Điện toán đám mây thế hệ mới, Kubernetes, Microservices kiến trúc cao cấp và thực hành bảo mật DevSecOps trong môi trường đa đám mây (Multi-Cloud).",
    },
    {
        "title": "Vietnam UI/UX Design & Product Innovation Forum 2026",
        "slug": "vietnam-uiux-design-product-innovation-2026",
        "category_code": "UIUX",
        "event_type": "Thiết Kế Trải Nghiệm",
        "location": "Dreamplex Coworking Space, TP. Hồ Chí Minh",
        "location_address": "195 Điện Biên Phủ, Phường 15, Bình Thạnh, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Dreamplex+195+Dien+Bien+Phu&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "18/11/2026 08:30",
        "end_date": "19/11/2026 17:00",
        "start_time": datetime(2026, 11, 18, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 19, 17, 0, tzinfo=timezone.utc),
        "capacity": 450,
        "registered_count": 380,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 6,
        "cover_image": IMAGES["uiux"],
        "description": "Diễn đàn hàng đầu về thiết kế trải nghiệm người dùng, xây dựng Design System quy mô lớn, tương tác đa giác quan và ứng dụng AI hỗ trợ quy trình thiết kế giao diện sản phẩm số.",
    },
    {
        "title": "TechFest Global Innovation & Startup Summit 2026",
        "slug": "techfest-global-innovation-2026",
        "category_code": "STARTUP",
        "event_type": "Khởi Nghiệp",
        "location": "Trung Tâm Hội Chợ & Triển Lãm Sài Gòn (SECC), TP. Hồ Chí Minh",
        "location_address": "799 Nguyễn Văn Linh, Tân Phú, Quận 7, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=SECC+Quan+7+Ho+Chi+Minh&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "25/10/2026 08:00",
        "end_date": "27/10/2026 18:00",
        "start_time": datetime(2026, 10, 25, 8, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 27, 18, 0, tzinfo=timezone.utc),
        "capacity": 1000,
        "registered_count": 890,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 7,
        "cover_image": IMAGES["techfest"],
        "description": "Ngày hội đổi mới sáng tạo quốc tế kết nối hơn 300 quỹ đầu tư mạo hiểm (VCs), 500 startup công nghệ đột phá và các lãnh đạo công nghệ nhằm thúc đẩy hệ sinh thái khởi nghiệp kỳ lân.",
    },
    {
        "title": "Web3 & Blockchain Developers Conclave 2026",
        "slug": "web3-blockchain-developers-conclave-2026",
        "category_code": "BLOCKCHAIN",
        "event_type": "Blockchain & Web3",
        "location": "Keangnam Hanoi Landmark Tower",
        "location_address": "Tòa nhà Keangnam Landmark 72, Mễ Trì, Cầu Giấy, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Keangnam+Hanoi+Landmark+Tower&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "15/09/2026 08:30",
        "end_date": "16/09/2026 17:30",
        "start_time": datetime(2026, 9, 15, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 9, 16, 17, 30, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 480,
        "status": "COMPLETED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 8,
        "cover_image": IMAGES["blockchain"],
        "description": "Nơi quy tụ các lập trình viên hàng đầu hệ sinh thái Web3, phân tích chuyên sâu về Layer 2 rollups, Smart Contract Security, Zero-Knowledge Proofs và tài chính phi tập trung (DeFi 3.0).",
    },
    {
        "title": "Hội Thảo Quốc Tế: Đạo Đức Trong Kỷ Nguyên Trí Tuệ Nhân Tạo",
        "slug": "dao-duc-trong-ky-nguyen-ai",
        "category_code": "AI",
        "event_type": "Đạo Đức AI",
        "location": "Trường Đại học VinUniversity, Hà Nội",
        "location_address": "Khu đô thị Vinhomes Ocean Park, Đa Tốn, Gia Lâm, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=VinUniversity+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "12/09/2026 09:00",
        "end_date": "13/09/2026 17:00",
        "start_time": datetime(2026, 9, 12, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 9, 13, 17, 0, tzinfo=timezone.utc),
        "capacity": 400,
        "registered_count": 385,
        "status": "COMPLETED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 9,
        "cover_image": IMAGES["ai_ethics"],
        "description": "Diễn đàn học thuật chuyên sâu về các nguyên tắc đạo đức AI, tính minh bạch của mô hình ngôn ngữ lớn (LLMs), giải quyết thiên vị dữ liệu và khuôn khổ pháp lý quốc tế cho Trí tuệ nhân tạo.",
    },
    {
        "title": "Workshop Chuyên Sâu: Xây Dựng AI Agents Với LangGraph & pgvector",
        "slug": "workshop-ai-agents-langgraph-pgvector",
        "category_code": "AI",
        "event_type": "Workshop AI",
        "location": "Dreamplex Coworking Space, TP. Hồ Chí Minh",
        "location_address": "195 Điện Biên Phủ, Phường 15, Bình Thạnh, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Dreamplex+195+Dien+Bien+Phu&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "25/09/2026 08:30",
        "end_date": "25/09/2026 17:30",
        "start_time": datetime(2026, 9, 25, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 9, 25, 17, 30, tzinfo=timezone.utc),
        "capacity": 300,
        "registered_count": 295,
        "status": "ONGOING",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 10,
        "cover_image": IMAGES["langgraph"],
        "description": "Lớp đào tạo thực hành chuyên sâu hướng dẫn kỹ sư lập trình Multi-Agent Workflows, RAG kết hợp Vector Database pgvector trên PostgreSQL và triển khai mô hình Human-in-the-Loop.",
    },
    {
        "title": "Diễn Đàn Chuyển Đổi Số Doanh Nghiệp & Smart Manufacturing",
        "slug": "chuyen-doi-so-doanh-nghiep-smart-manufacturing",
        "category_code": "DIGITAL",
        "event_type": "Chuyển Đổi Số",
        "location": "Khách sạn Sheraton Saigon Hotel & Towers",
        "location_address": "88 Đồng Khởi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Sheraton+Saigon+Hotel&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "22/09/2026 09:00",
        "end_date": "23/09/2026 16:30",
        "start_time": datetime(2026, 9, 22, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 9, 23, 16, 30, tzinfo=timezone.utc),
        "capacity": 450,
        "registered_count": 420,
        "status": "COMPLETED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 11,
        "cover_image": IMAGES["smart_mfg"],
        "description": "Giới thiệu giải pháp nhà máy thông minh Smart Factory 4.0, tự động hóa chuỗi cung ứng với IoT công nghiệp và phân tích dữ liệu sản xuất dự đoán bảo trì chính xác bằng AI.",
    },
    {
        "title": "Hội Nghị Nhà Phát Triển Game & Ứng Dụng Đồ Họa 3D Thời Gian Thực",
        "slug": "hoi-nghi-game-developers-do-hoa-3d-2026",
        "category_code": "SOFTWARE",
        "event_type": "Game & 3D",
        "location": "Nhà Thi Đấu Thể Thao Phú Thọ, TP. Hồ Chí Minh",
        "location_address": "219 Lý Thường Kiệt, Phường 15, Quận 11, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Nha+Thi+Dau+Phu+Tho+TPHCM&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "26/09/2026 09:00",
        "end_date": "27/09/2026 18:00",
        "start_time": datetime(2026, 9, 26, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 9, 27, 18, 0, tzinfo=timezone.utc),
        "capacity": 800,
        "registered_count": 630,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 12,
        "cover_image": IMAGES["game_dev"],
        "description": "Sự kiện thường niên lớn nhất dành cho game developers, 3D artists với các chủ đề đồ họa Unreal Engine 5, ray-tracing phần cứng, sinh tài nguyên 3D bằng Generative AI.",
    },
    {
        "title": "Triển Lãm Robot & Tự Động Hóa Công Nghiệp Thông Minh 2026",
        "slug": "trien-lam-robot-tu-dong-hoa-2026",
        "category_code": "ROBOTICS",
        "event_type": "Robot & Tự Động Hóa",
        "location": "Trung Tâm Triển Lãm Quốc Tế WTC Expo Bình Dương",
        "location_address": "Số A19 đường Hùng Vương, Phường Hòa Phú, TP. Thủ Dầu Một, Bình Dương",
        "google_maps_url": "https://maps.google.com/maps?q=WTC+Expo+Binh+Duong&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "02/10/2026 09:00",
        "end_date": "04/10/2026 17:00",
        "start_time": datetime(2026, 10, 2, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 4, 17, 0, tzinfo=timezone.utc),
        "capacity": 950,
        "registered_count": 710,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 13,
        "cover_image": IMAGES["robotics"],
        "description": "Trưng bày hơn 200 dòng robot tự hành (AGV/AMR), cánh tay robot công nghiệp thế hệ mới, thị giác máy tính Computer Vision cho dây chuyền đóng gói và thiết bị không người lái.",
    },
    {
        "title": "Hội Thảo Quốc Tế Semiconductor & Chip Thiết Kế Vi Mạch",
        "slug": "semiconductor-chip-thiet-ke-vi-mach",
        "category_code": "SEMICONDUCTOR",
        "event_type": "Bán Dẫn & Vi Mạch",
        "location": "Khu Công Nghệ Cao TP. Hồ Chí Minh (SHTP)",
        "location_address": "Đường D1, Phường Tân Phú, TP. Thủ Đức, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Saigon+Hi-Tech+Park+TP+Thu+Duc&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "06/10/2026 08:30",
        "end_date": "07/10/2026 17:00",
        "start_time": datetime(2026, 10, 6, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 7, 17, 0, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 410,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 14,
        "cover_image": IMAGES["semiconductor"],
        "description": "Tọa đàm hợp tác chiến lược giữa các tập đoàn bán dẫn hàng đầu toàn cầu, viện nghiên cứu và trường đại học nhằm đào tạo nhân lực thiết kế chip vi mạch bán dẫn.",
    },
    {
        "title": "Data Engineering & Big Data Analytics Forum 2026",
        "slug": "data-engineering-big-data-analytics-2026",
        "category_code": "DATA",
        "event_type": "Dữ Liệu & Big Data",
        "location": "Tòa Nhà FPT Tower Cầu Giấy, Hà Nội",
        "location_address": "Số 10 Phạm Văn Bạch, Dịch Vọng, Cầu Giấy, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=FPT+Tower+Pham+Van+Bach+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "14/10/2026 09:00",
        "end_date": "15/10/2026 17:30",
        "start_time": datetime(2026, 10, 14, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 15, 17, 30, tzinfo=timezone.utc),
        "capacity": 600,
        "registered_count": 430,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 15,
        "cover_image": IMAGES["data_eng"],
        "description": "Khám phá kiến trúc Data Lakehouse hiện đại, xử lý luồng dữ liệu thời gian thực quy mô Terabyte với Apache Kafka/Flink và tối ưu hóa chi phí lưu trữ đám mây.",
    },
    {
        "title": "Hội Nghị Y Tế Thông Minh & MedTech Innovation 2026",
        "slug": "hoi-nghi-y-te-thong-minh-medtech-2026",
        "category_code": "MEDTECH",
        "event_type": "Y Tế Thông Minh",
        "location": "Khách sạn InterContinental Hanoi Landmark72",
        "location_address": "Tòa nhà Keangnam Hanoi Landmark, E6 Phạm Hùng, Cầu Giấy, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=InterContinental+Hanoi+Landmark72&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "22/10/2026 08:30",
        "end_date": "23/10/2026 17:00",
        "start_time": datetime(2026, 10, 22, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 23, 17, 0, tzinfo=timezone.utc),
        "capacity": 450,
        "registered_count": 310,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 16,
        "cover_image": IMAGES["medtech"],
        "description": "Ứng dụng AI phân tích hình ảnh y tế, chẩn đoán bệnh lý chính xác, hồ sơ bệnh án điện tử tập trung (EMR) và công nghệ giải trình tự gen hỗ trợ y học cá thể hóa.",
    },
    {
        "title": "Hội Nghị EdTech Vietnam: Chuyển Đổi Số Giáo Dục & AI",
        "slug": "edtech-vietnam-chuyen-doi-so-giao-duc-2026",
        "category_code": "EDTECH",
        "event_type": "Giáo Dục & EdTech",
        "location": "Trường Đại Học Bách Khoa Hà Nội",
        "location_address": "Số 1 Đại Cồ Việt, Bách Khoa, Hai Bà Trưng, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Dai+Hoc+Bach+Khoa+Ha+Noi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "28/10/2026 08:30",
        "end_date": "29/10/2026 17:00",
        "start_time": datetime(2026, 10, 28, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 10, 29, 17, 0, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 350,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 17,
        "cover_image": IMAGES["edtech"],
        "description": "Nâng cao chất lượng dạy và học qua nền tảng thích ứng theo năng lực cá nhân bằng AI, lớp học ảo Metaverse và tài nguyên giáo dục mở chuẩn quốc tế.",
    },
    {
        "title": "Hội Thảo Smart City & Giao Thông Thông Minh 2026",
        "slug": "smart-city-giao-thong-thong-minh-2026",
        "category_code": "SMARTCITY",
        "event_type": "Đô Thị Thông Minh",
        "location": "Trung Tâm Hành Chính TP. Đà Nẵng",
        "location_address": "24 Trần Phú, Thạch Thang, Hải Châu, Đà Nẵng",
        "google_maps_url": "https://maps.google.com/maps?q=Trung+Tam+Hanh+Chinh+Da+Nang&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "08/11/2026 08:30",
        "end_date": "09/11/2026 17:00",
        "start_time": datetime(2026, 11, 8, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 9, 17, 0, tzinfo=timezone.utc),
        "capacity": 450,
        "registered_count": 320,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 18,
        "cover_image": IMAGES["smartcity"],
        "description": "Mô hình vận hành đô thị thông minh tích hợp cảm biến IoT điều tiết đèn giao thông theo mật độ thực tế, giám sát chất lượng không khí và hạ tầng số.",
    },
    {
        "title": "Vietnam AgriTech: Đột Phá Nông Nghiệp Công Nghệ Cao 2026",
        "slug": "vietnam-agritech-nong-nghiep-cong-nghe-cao-2026",
        "category_code": "AGRITECH",
        "event_type": "Nông Nghiệp Công Nghệ Cao",
        "location": "Khách sạn Mường Thanh Luxury Cần Thơ",
        "location_address": "Khu E1, Cồn Cái Khế, Ninh Kiều, Cần Thơ",
        "google_maps_url": "https://maps.google.com/maps?q=Muong+Thanh+Luxury+Can+Tho&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "15/11/2026 08:30",
        "end_date": "16/11/2026 17:00",
        "start_time": datetime(2026, 11, 15, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 16, 17, 0, tzinfo=timezone.utc),
        "capacity": 400,
        "registered_count": 260,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 19,
        "cover_image": IMAGES["agritech"],
        "description": "Giới thiệu máy bay không người lái phun tưới chính xác, hệ thống cảm biến độ ẩm đất IoT tự động, truy xuất nguồn gốc nông sản bằng Blockchain.",
    },
    {
        "title": "AI Hackathon & Demo Day: Future Innovators 2026",
        "slug": "ai-hackathon-demo-day-future-innovators-2026",
        "category_code": "HACKATHON",
        "event_type": "Hackathon & Đổi Mới",
        "location": "Đại Học FPT TP. Hồ Chí Minh",
        "location_address": "Lô E2a-7, Đường D1, Khu Công nghệ cao, Long Thạnh Mỹ, TP. Thủ Đức, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=FPT+University+HCMC&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "21/11/2026 08:00",
        "end_date": "22/11/2026 21:00",
        "start_time": datetime(2026, 11, 21, 8, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 22, 21, 0, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 460,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 20,
        "cover_image": IMAGES["hackathon"],
        "description": "48 giờ lập trình liên tục thử thách các tài năng trẻ sáng tạo các ứng dụng AI tạo sinh, Agentic workflows giải quyết các bài toán cấp bách với tổng giải thưởng 1 tỷ VNĐ.",
    },

    # =========================================================================
    # 17 SỰ KIỆN MỚI BỔ SUNG (NÂNG TỔNG SỐ THÀNH 37 SỰ KIỆN THỰC TẾ ĐA DẠNG)
    # =========================================================================
    {
        "title": "Vietnam Smart Logistics & Supply Chain Automation Summit 2026",
        "slug": "vietnam-smart-logistics-supply-chain-2026",
        "category_code": "LOGISTICS",
        "event_type": "Logistics & Supply Chain",
        "location": "Trung Tâm Hội Chợ Triển Lãm Quốc Tế Hải Phòng",
        "location_address": "Số 10 Phạm Văn Đồng, Dương Kinh, TP. Hải Phòng",
        "google_maps_url": "https://maps.google.com/maps?q=Hai+Phong+International+Exhibition+Center&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "28/11/2026 08:30",
        "end_date": "29/11/2026 17:00",
        "start_time": datetime(2026, 11, 28, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 11, 29, 17, 0, tzinfo=timezone.utc),
        "capacity": 550,
        "registered_count": 390,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 21,
        "cover_image": IMAGES["logistics"],
        "description": "Ứng dụng robot AGV/AMR trong kho vận thông minh, tối ưu hóa tuyến đường vận tải bằng AI và giải pháp quản lý cảng biển thông minh thế hệ mới.",
    },
    {
        "title": "Vietnam Electric Vehicle (EV) & Smart Mobility Forum 2026",
        "slug": "vietnam-ev-smart-mobility-forum-2026",
        "category_code": "GREENTECH",
        "event_type": "Xe Điện & Giao Thông Xanh",
        "location": "Khách Sạn Pullman Danang Beach Resort",
        "location_address": "101 Võ Nguyên Giáp, Phường Khuê Mỹ, Quận Ngũ Hành Sơn, Đà Nẵng",
        "google_maps_url": "https://maps.google.com/maps?q=Pullman+Danang+Beach+Resort&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "01/12/2026 09:00",
        "end_date": "02/12/2026 17:00",
        "start_time": datetime(2026, 12, 1, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 2, 17, 0, tzinfo=timezone.utc),
        "capacity": 600,
        "registered_count": 430,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 22,
        "cover_image": IMAGES["ev_mobility"],
        "description": "Diễn đàn hàng đầu về hạ tầng trạm sạc xe điện siêu nhanh, công nghệ pin thể rắn thế hệ mới và chính sách phát triển phương tiện giao thông xanh tại đô thị.",
    },
    {
        "title": "Hội Thảo Quốc Tế: Điện Toán Lượng Tử & Vật Liệu Tiên Tiến 2026",
        "slug": "dien-toan-luong-tu-deeptech-2026",
        "category_code": "DEEPTECH",
        "event_type": "Điện Toán Lượng Tử",
        "location": "Viện Hàn Lâm Khoa Học và Công Nghệ Việt Nam (VAST)",
        "location_address": "18 Hoàng Quốc Việt, Nghĩa Đô, Cầu Giấy, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Vietnam+Academy+of+Science+and+Technology+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "03/12/2026 08:30",
        "end_date": "04/12/2026 17:00",
        "start_time": datetime(2026, 12, 3, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 4, 17, 0, tzinfo=timezone.utc),
        "capacity": 400,
        "registered_count": 310,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 23,
        "cover_image": IMAGES["quantum"],
        "description": "Tọa đàm chuyên sâu về thuật toán lượng tử, mã hóa hậu lượng tử (Post-Quantum Cryptography), siêu máy tính và vật liệu bán dẫn hai chiều tương lai.",
    },
    {
        "title": "Vietnam E-Commerce Innovation & Live-Commerce Summit 2026",
        "slug": "vietnam-ecommerce-live-commerce-summit-2026",
        "category_code": "DIGITAL",
        "event_type": "Thương Mại Điện Tử",
        "location": "Trung Tâm Hội Nghị The Adora Center, TP. Hồ Chí Minh",
        "location_address": "431 Hoàng Văn Thụ, Phường 4, Quận Tân Bình, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=The+Adora+Center+Hoang+Van+Thu&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "05/12/2026 08:30",
        "end_date": "06/12/2026 18:00",
        "start_time": datetime(2026, 12, 5, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 6, 18, 0, tzinfo=timezone.utc),
        "capacity": 900,
        "registered_count": 760,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 24,
        "cover_image": IMAGES["ecommerce"],
        "description": "Bùng nổ xu hướng Live-Commerce, cá nhân hóa trải nghiệm mua sắm bằng Generative AI và thanh toán một chạm thế hệ mới trên các sàn thương mại điện tử.",
    },
    {
        "title": "Future of Work & HR Technology Conference Vietnam 2026",
        "slug": "future-of-work-hr-tech-vietnam-2026",
        "category_code": "DIGITAL",
        "event_type": "Công Nghệ Nhân Sự & HR Tech",
        "location": "Khách Sạn Pan Pacific Hanoi",
        "location_address": "Số 1 Đường Thanh Niên, Ba Đình, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Pan+Pacific+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "08/12/2026 09:00",
        "end_date": "09/12/2026 17:00",
        "start_time": datetime(2026, 12, 8, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 9, 17, 0, tzinfo=timezone.utc),
        "capacity": 450,
        "registered_count": 340,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 25,
        "cover_image": IMAGES["hr_tech"],
        "description": "Ứng dụng AI trong tuyển dụng và đánh giá năng lực nhân tài, mô hình làm việc kết hợp linh hoạt (Hybrid Work) và nâng cao trải nghiệm số của nhân viên.",
    },
    {
        "title": "Vietnam PropTech & Smart Building Expo 2026",
        "slug": "vietnam-proptech-smart-building-expo-2026",
        "category_code": "SMARTCITY",
        "event_type": "Công Nghệ Bất Động Sản",
        "location": "Trung Tâm Hội Nghị Riverside Palace, TP. Hồ Chí Minh",
        "location_address": "360D Bến Vân Đồn, Phường 1, Quận 4, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Riverside+Palace+Ben+Van+Don&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "10/12/2026 08:30",
        "end_date": "11/12/2026 17:00",
        "start_time": datetime(2026, 12, 10, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 11, 17, 0, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 370,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 26,
        "cover_image": IMAGES["proptech"],
        "description": "Triển lãm công nghệ quản lý tòa nhà thông minh BMS, mô hình thông tin công trình BIM, thực tế ảo tham quan dự án và số hóa tài sản bất động sản.",
    },
    {
        "title": "Vietnam Open Source & Linux Developers Summit 2026",
        "slug": "vietnam-open-source-summit-2026",
        "category_code": "SOFTWARE",
        "event_type": "Mã Nguồn Mở & Linux",
        "location": "Trường Đại học Khoa học Tự nhiên - ĐHQG Hà Nội",
        "location_address": "334 Nguyễn Trãi, Thanh Xuân Trung, Thanh Xuân, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Dai+Hoc+Khoa+Hoc+Tu+Nhien+Ha+Noi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "12/12/2026 08:30",
        "end_date": "13/12/2026 17:30",
        "start_time": datetime(2026, 12, 12, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 13, 17, 30, tzinfo=timezone.utc),
        "capacity": 650,
        "registered_count": 520,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 27,
        "cover_image": IMAGES["opensource"],
        "description": "Đại hội cộng đồng lập trình viên mã nguồn mở, chia sẻ kinh nghiệm đóng góp dự án GitHub/Linux Kernel, bảo mật phần mềm Supply Chain và giấy phép mã nguồn mở.",
    },
    {
        "title": "SpaceTech & Satellite Communications Forum Vietnam 2026",
        "slug": "spacetech-satellite-communications-vietnam-2026",
        "category_code": "DEEPTECH",
        "event_type": "Công Nghệ Vũ Trụ",
        "location": "Trung Tâm Vũ Trụ Việt Nam (VNSC), Khu CNC Hòa Lạc",
        "location_address": "Km 29 Đại lộ Thăng Long, Thạch Thất, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Vietnam+National+Space+Center+Hoa+Lac&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "14/12/2026 09:00",
        "end_date": "15/12/2026 16:30",
        "start_time": datetime(2026, 12, 14, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 15, 16, 30, tzinfo=timezone.utc),
        "capacity": 350,
        "registered_count": 260,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 28,
        "cover_image": IMAGES["spacetech"],
        "description": "Khám phá công nghệ chế tạo vệ tinh nhỏ quan sát trái đất, viễn thám phục vụ cảnh báo thiên tai, nông nghiệp thông minh và internet vệ tinh quỹ đạo thấp LEO.",
    },
    {
        "title": "AI Marketing & Creative Content Creation Forum 2026",
        "slug": "ai-marketing-content-creation-forum-2026",
        "category_code": "AI",
        "event_type": "AI Marketing & Sáng Tạo",
        "location": "Khách Sạn Caravelle Saigon",
        "location_address": "19-23 Lam Sơn Square, Bến Nghé, Quận 1, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Caravelle+Saigon&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "16/12/2026 08:30",
        "end_date": "17/12/2026 17:00",
        "start_time": datetime(2026, 12, 16, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 17, 17, 0, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 440,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 29,
        "cover_image": IMAGES["aimarketing"],
        "description": "Chiến lược ứng dụng AI tạo sinh trong sản xuất video, tối ưu chiến dịch quảng cáo đa kênh tự động và cá nhân hóa thông điệp tiếp thị thương hiệu.",
    },
    {
        "title": "Vietnam BioTechnology & Genome Engineering Conference 2026",
        "slug": "vietnam-biotech-genome-engineering-2026",
        "category_code": "MEDTECH",
        "event_type": "Công Nghệ Sinh Học",
        "location": "Viện Hàn Lâm Khoa Học và Công Nghệ Việt Nam, Hà Nội",
        "location_address": "18 Hoàng Quốc Việt, Cầu Giấy, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Institute+of+Biotechnology+VAST+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "18/12/2026 08:30",
        "end_date": "19/12/2026 17:00",
        "start_time": datetime(2026, 12, 18, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 19, 17, 0, tzinfo=timezone.utc),
        "capacity": 400,
        "registered_count": 290,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 30,
        "cover_image": IMAGES["biotech"],
        "description": "Diễn đàn chuyên môn về công nghệ chỉnh sửa gen CRISPR, giải trình tự gen thế hệ mới phục vụ y học chính xác và bảo tồn đa dạng sinh học.",
    },
    {
        "title": "Vietnam 5G/6G Infrastructure & Edge Cloud Summit 2026",
        "slug": "vietnam-5g-6g-edge-cloud-summit-2026",
        "category_code": "CLOUD",
        "event_type": "Hạ Tầng Viễn Thông 5G/6G",
        "location": "Tòa Nhà Viettel Telecom Cầu Giấy, Hà Nội",
        "location_address": "Số 1 Trần Hữu Dực, Mỹ Đình, Nam Từ Liêm, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Viettel+Headquarters+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "20/12/2026 09:00",
        "end_date": "21/12/2026 17:00",
        "start_time": datetime(2026, 12, 20, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 21, 17, 0, tzinfo=timezone.utc),
        "capacity": 700,
        "registered_count": 510,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 31,
        "cover_image": IMAGES["telecom_edge"],
        "description": "Đẩy mạnh thương mại hóa mạng 5G Advanced độc lập (SA), nghiên cứu tiền trạm 6G và triển khai tính toán biên (Multi-Access Edge Computing) độ trễ siêu thấp.",
    },
    {
        "title": "Spatial Computing & AR/VR Developers Expo Vietnam 2026",
        "slug": "spatial-computing-ar-vr-expo-vietnam-2026",
        "category_code": "SOFTWARE",
        "event_type": "Điện Toán Không Gian & AR/VR",
        "location": "Trung Tâm Hội Chợ & Triển Lãm Sài Gòn (SECC), TP. Hồ Chí Minh",
        "location_address": "799 Nguyễn Văn Linh, Tân Phú, Quận 7, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=SECC+Quan+7+Ho+Chi+Minh&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "22/12/2026 09:00",
        "end_date": "23/12/2026 18:00",
        "start_time": datetime(2026, 12, 22, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 23, 18, 0, tzinfo=timezone.utc),
        "capacity": 800,
        "registered_count": 620,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 32,
        "cover_image": IMAGES["spatial_arvr"],
        "description": "Trải nghiệm kính thực tế ảo tăng cường thế hệ mới, phát triển ứng dụng Spatial Computing trên VisionOS, Unity, WebXR phục vụ giáo dục và đào tạo kỹ thuật.",
    },
    {
        "title": "Vietnam InsurTech & Digital Underwriting Summit 2026",
        "slug": "vietnam-insurtech-digital-underwriting-2026",
        "category_code": "FINTECH",
        "event_type": "Bảo Hiểm Công Nghệ",
        "location": "Khách Sạn Meliá Hanoi",
        "location_address": "44B Lý Thường Kiệt, Trần Hưng Đạo, Hoàn Kiếm, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=Melia+Hanoi+Hotel&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "24/12/2026 08:30",
        "end_date": "25/12/2026 16:30",
        "start_time": datetime(2026, 12, 24, 8, 30, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 25, 16, 30, tzinfo=timezone.utc),
        "capacity": 450,
        "registered_count": 315,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 33,
        "cover_image": IMAGES["insurtech"],
        "description": "Tự động hóa quy trình thẩm định bảo hiểm, bồi thường trực tuyến siêu tốc bằng AI và dữ liệu viễn thông Telematics bảo hiểm phương tiện cá nhân hóa.",
    },
    {
        "title": "Vietnam CleanTech & Circular Economy Forum 2026",
        "slug": "vietnam-cleantech-circular-economy-2026",
        "category_code": "GREENTECH",
        "event_type": "Công Nghệ Môi Trường",
        "location": "Khách Sạn The Imperial Hotel Vũng Tàu",
        "location_address": "159 Thùy Vân, Phường Thắng Tam, TP. Vũng Tàu, Bà Rịa - Vũng Tàu",
        "google_maps_url": "https://maps.google.com/maps?q=The+Imperial+Hotel+Vung+Tau&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "26/12/2026 09:00",
        "end_date": "27/12/2026 17:00",
        "start_time": datetime(2026, 12, 26, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 27, 17, 0, tzinfo=timezone.utc),
        "capacity": 400,
        "registered_count": 280,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 34,
        "cover_image": IMAGES["cleantech"],
        "description": "Giải pháp tái chế rác thải điện tử công nghệ cao, xử lý nước tuần hoàn không xả thải và vật liệu sinh học tự phân hủy thay thế đồ nhựa dùng một lần.",
    },
    {
        "title": "Vietnam National Cyber Defense & Red Team Drill 2026",
        "slug": "vietnam-cyber-defense-red-team-drill-2026",
        "category_code": "CYBERSECURITY",
        "event_type": "Diễn Tập An Ninh Mạng Quốc Gia",
        "location": "Trung Tâm Giám Sát An Toàn Không Gian Mạng Quốc Gia (NCSC)",
        "location_address": "Tòa nhà Cục An Toàn Thông Tin, Yên Hòa, Cầu Giấy, Hà Nội",
        "google_maps_url": "https://maps.google.com/maps?q=National+Cyber+Security+Center+Hanoi&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "28/12/2026 08:00",
        "end_date": "28/12/2026 18:00",
        "start_time": datetime(2026, 12, 28, 8, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 28, 18, 0, tzinfo=timezone.utc),
        "capacity": 350,
        "registered_count": 310,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 35,
        "cover_image": IMAGES["cyberdrill"],
        "description": "Diễn tập thực chiến phòng thủ an ninh mạng quy mô quốc gia giữa các đội Red Team (Tấn công) và Blue Team (Phòng thủ) bảo vệ hạ tầng trọng yếu.",
    },
    {
        "title": "Vietnam Web3 Gaming & Virtual Economies Summit 2026",
        "slug": "vietnam-web3-gaming-virtual-economies-2026",
        "category_code": "BLOCKCHAIN",
        "event_type": "Web3 Gaming & Kinh Tế Số",
        "location": "Khách Sạn Novotel Danang Premier Han River",
        "location_address": "36 Bạch Đằng, Thạch Thang, Hải Châu, Đà Nẵng",
        "google_maps_url": "https://maps.google.com/maps?q=Novotel+Danang+Premier+Han+River&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "29/12/2026 09:00",
        "end_date": "30/12/2026 17:30",
        "start_time": datetime(2026, 12, 29, 9, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 30, 17, 30, tzinfo=timezone.utc),
        "capacity": 500,
        "registered_count": 395,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 36,
        "cover_image": IMAGES["web3gaming"],
        "description": "Mô hình kinh tế số cân bằng trong game thế hệ mới, sở hữu tài sản kỹ thuật số phi tập trung và cơ chế chống lạm phát token trong hệ sinh thái gaming.",
    },
    {
        "title": "Vietnam CIO & CTO Leadership Summit: Horizon 2027",
        "slug": "vietnam-cio-cto-leadership-summit-2026",
        "category_code": "DIGITAL",
        "event_type": "Lãnh Đạo Công Nghệ Cấp Cao",
        "location": "Khách Sạn Park Hyatt Saigon, TP. Hồ Chí Minh",
        "location_address": "Số 2 Công Trường Lam Sơn, Bến Nghé, Quận 1, TP. Hồ Chí Minh",
        "google_maps_url": "https://maps.google.com/maps?q=Park+Hyatt+Saigon&t=&z=16&ie=UTF8&iwloc=&output=embed",
        "start_date": "30/12/2026 14:00",
        "end_date": "31/12/2026 18:00",
        "start_time": datetime(2026, 12, 30, 14, 0, tzinfo=timezone.utc),
        "end_time": datetime(2026, 12, 31, 18, 0, tzinfo=timezone.utc),
        "capacity": 300,
        "registered_count": 260,
        "status": "PUBLISHED",
        "featured": False,
        "homepage_visible": True,
        "homepage_order": 37,
        "cover_image": IMAGES["cio_summit"],
        "description": "Diễn đàn kín dành cho 300 Giám đốc Công nghệ (CTO) và Giám đốc CNTT (CIO) hàng đầu hoạch định chiến lược đầu tư công nghệ và định hình chuyển đổi số giai đoạn 2027.",
    },
]


async def seed_20_realistic_events() -> int:
    """
    Seeds 37 production-grade realistic technology, AI, and innovation events
    for Vietnam & Global in Sept-Dec 2026 (including 17 newly added events).
    4 Featured events represent 4 distinct pillars: AI, Fintech, Cybersecurity, Green Tech.
    Cleans up any old test events while preserving core relations.
    """
    print(">>> Starting Force Seed 37 Realistic Events (20 initial + 17 new)...")
    async with AsyncSessionLocal() as db:
        # 1. Ensure Categories
        category_map: Dict[str, int] = {}
        for cat_info in CATEGORIES_DATA:
            res = await db.execute(select(EventCategory).where(EventCategory.code == cat_info["code"]))
            cat = res.scalar_one_or_none()
            if not cat:
                cat = EventCategory(name=cat_info["name"], code=cat_info["code"])
                db.add(cat)
                await db.flush()
            category_map[cat_info["code"]] = cat.id

        # Also get or fallback default category ID 1
        res1 = await db.execute(select(EventCategory).where(EventCategory.id == 1))
        cat1 = res1.scalar_one_or_none()
        default_cat_id = cat1.id if cat1 else list(category_map.values())[0]

        # 2. Identify & Clean up hash-suffixed test events (e.g. "AI Summit Vietnam 2026 db3f53")
        # Keep event ID 1 intact (we will update it to Event #1)
        all_events_res = await db.execute(select(Event).order_by(Event.id.asc()))
        existing_events = all_events_res.scalars().all()
        
        hash_pattern = re.compile(r'\s+[0-9a-f]{6}$')
        for ev in existing_events:
            if ev.id != 1 and (hash_pattern.search(ev.title) or "Test" in ev.title or "test" in (ev.slug or '')):
                print(f"Cleaning up test event: ID {ev.id} - '{ev.title}'")
                await db.delete(ev)
        await db.commit()

        # 3. Seed / Update 20 events
        count = 0
        seeded_ids = set()
        for idx, ev_data in enumerate(RAW_EVENTS):
            cat_id = category_map.get(ev_data["category_code"], default_cat_id)
            
            # For the very first event, always bind to ID 1 if ID 1 exists
            target_event = None
            if idx == 0:
                res = await db.execute(select(Event).where(Event.id == 1))
                target_event = res.scalar_one_or_none()
            
            if not target_event:
                # Search by slug or title
                res = await db.execute(
                    select(Event).where(
                        (Event.slug == ev_data["slug"]) | (Event.title == ev_data["title"])
                    )
                )
                target_event = res.scalar_one_or_none()

            if target_event:
                # Update existing
                target_event.title = ev_data["title"]
                target_event.slug = ev_data["slug"]
                target_event.description = ev_data["description"]
                target_event.category_id = cat_id
                target_event.event_type = ev_data["event_type"]
                target_event.location = ev_data["location"]
                target_event.location_address = ev_data["location_address"]
                target_event.google_maps_url = ev_data["google_maps_url"]
                target_event.start_date = ev_data["start_date"]
                target_event.end_date = ev_data["end_date"]
                target_event.start_time = ev_data["start_time"]
                target_event.end_time = ev_data["end_time"]
                target_event.capacity = ev_data["capacity"]
                target_event.registered_count = ev_data["registered_count"]
                target_event.status = ev_data["status"]
                target_event.featured = ev_data["featured"]
                target_event.homepage_visible = ev_data["homepage_visible"]
                target_event.homepage_order = ev_data["homepage_order"]
                target_event.cover_image = ev_data["cover_image"]
                print(f"Updated event [{target_event.id}]: ({ev_data['event_type']}) {target_event.title}")
            else:
                # Insert new
                new_ev = Event(
                    title=ev_data["title"],
                    slug=ev_data["slug"],
                    description=ev_data["description"],
                    category_id=cat_id,
                    event_type=ev_data["event_type"],
                    location=ev_data["location"],
                    location_address=ev_data["location_address"],
                    google_maps_url=ev_data["google_maps_url"],
                    start_date=ev_data["start_date"],
                    end_date=ev_data["end_date"],
                    start_time=ev_data["start_time"],
                    end_time=ev_data["end_time"],
                    capacity=ev_data["capacity"],
                    registered_count=ev_data["registered_count"],
                    status=ev_data["status"],
                    featured=ev_data["featured"],
                    homepage_visible=ev_data["homepage_visible"],
                    homepage_order=ev_data["homepage_order"],
                    cover_image=ev_data["cover_image"],
                )
                db.add(new_ev)
                await db.flush()
                target_event = new_ev
                print(f"Created new event [{target_event.id}]: ({ev_data['event_type']}) {target_event.title}")

            seeded_ids.add(target_event.id)
            count += 1
            # Sync knowledge base RAG embedding asynchronously (safe fallback)
            try:
                await rag_engine.sync_event_knowledge(db, target_event, action="UPSERT")
            except Exception as e:
                print(f"Warning: RAG sync skipped for event {target_event.id}: {e}")

        # Ensure only the seeded events remain in DB
        all_now = (await db.execute(select(Event))).scalars().all()
        for ev in all_now:
            if ev.id not in seeded_ids:
                print(f"Purging extra event: [{ev.id}] {ev.title}")
                await db.delete(ev)

        await db.commit()
        print(f"✅ Successfully seeded/updated {count} realistic events across all categories and 4 distinct featured pillars!")
        return count


if __name__ == "__main__":
    asyncio.run(seed_20_realistic_events())
